package org.example.hl7.server;

import ca.uhn.hl7v2.protocol.ReceivingApplicationExceptionHandler;

import java.util.Map;

public class Hl7ExceptionHandler implements ReceivingApplicationExceptionHandler {

    /**
     * Process an exception.
     *
     * @param theIncomingMessage  the incoming message. This is the raw message which was received from the external system
     * @param theIncomingMetadata Any metadata that accompanies the incoming message. See {@link ca.uhn.hl7v2.protocol.Transportable#getMetadata()}
     * @param theOutgoingMessage  the outgoing message. The response NAK message generated by HAPI.
     * @param ex                  the exception which was received
     * @return The new outgoing message. This can be set to the value provided
     * by HAPI in <code>outgoingMessage</code>, or may be replaced with
     * another message. <b>This method may not return <code>null</code></b>.
     */
    public String processException(String theIncomingMessage, Map<String, Object> theIncomingMetadata, String theOutgoingMessage, Exception ex) {

        /*
         * Handle exception.
         */

        return theOutgoingMessage;
    }

}
